### ISSUE TITLE
ipc-channel tests truncate received data to expected size

### ISSUE THREAD

**Issue by vvuk** [servo/ipc-channel#103]
I don't understand this -- every test truncates the received data to the expected size, e.g.:

https://github.com/servo/ipc-channel/blob/master/src/platform/test.rs#L28
https://github.com/servo/ipc-channel/blob/master/src/platform/test.rs#L139

Is it expected/allowed that you can receive more data than you send, or even a bigger buffer?!

I had a bug where I was accidentally sending data twice, and these tests were happily passing.

**Comment by jdm** [comment]
Let's remove it and see how the CI reacts! That does seem weird to me.

**Comment by jdm** [comment]
It dates back to the original macOS implementation, fwiw.

**Comment by antrik** [comment]
See https://github.com/servo/ipc-channel/issues/83
