### ISSUE TITLE
Note suggesting to use mkstemp or mkdtemp instead of mktemp

### ISSUE THREAD

**Issue by connorimes** [servo/ipc-channel#11]
FYI, I get the following note when building on ARM when everything is being linked at the end.  Don't recall if I saw it elsewhere.

<pre>
note: /local/servo/components/servo/target/debug/deps/libipc_channel-948af358b3c092a6.rlib(ipc_channel-948af358b3c092a6.0.o): In function `platform::linux::_$LT$impl$GT$::new::he43c9a17ef03c572fbb':
/home/username/.cargo/git/checkouts/ipc-channel-62de6a747162919c/master/platform/linux/mod.rs:433: warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
</pre>

**Comment by craftytrickster** [comment]
I am getting this message when trying to build servo as well on Linux (Ubuntu 14.04), with 
rust nightly date of - 2015-12-09
```
note: /usr/bin/ld.gold: error: cannot find -lEGL
/home/divad/Rust/servo/.cargo/git/checkouts/ipc-channel-3840821e54ea11a6/master/platform/linux/mod.rs:437: warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
collect2: error: ld returned 1 exit status

error: aborting due to previous error
Could not compile `servo`.
```

**Comment by antrik** [comment]
@craftytrickster FWIW, your error was never related to the issue here, which is just a warning. (Your actual error was the `cannot find -lEGL` bit.) Nevertheless, your PR addressing the warning should have been merged... Too bad I didn't know about it before :-(

**Comment by craftytrickster** [comment]
I haven't actually been able to contribute to servo in a really long time, so no worries! I'm glad you are able to resolve the issue though.
