### ISSUE TITLE
Use memfd for IPCSharedMemory on Linux

### ISSUE THREAD

**Issue by Manishearth** [servo/ipc-channel#125]
Currently on linux IPCSharedMemory is backed by a file in `/tmp`, which is often not tempfs, and ends up doing unnecessary disk IO.

If possible, we should use [`memfd_create()`](http://man7.org/linux/man-pages/man2/memfd_create.2.html) to take an existing memory buffer and make it into a file descriptor (which we can then share).

cc @antrik @pcwalton

**Comment by antrik** [comment]
@Manishearth this has been on my personal to-do list for a while...

I'm a bit ambivalent about actually using `memfd` though: while it's an elegant concept, it's Linux-only for now. As a first step, we should rather aim for a portable implementation based on the POSIX shared memory API ( http://man7.org/linux/man-pages/man7/shm_overview.7.html ) I'd say.

**Comment by Manishearth** [comment]
Works for me. Patrick had mentioned he preferred memfd over shmem though IIRC.

**Comment by danlrobertson** [comment]
This can be closed since #140 has been merged.

**Comment by emilio** [comment]
Yay, thanks for working on this @danlrobertson! :)
