### ISSUE TITLE
Compile time failure

### ISSUE THREAD

**Issue by danlrobertson** [servo/ipc-channel#154]
When using the latest nightly rustc and compiling on the master branch I get the following.

```
error[E0282]: type annotations needed
   --> src/ipc.rs:155:42
    |
155 |                     let mut serializer = bincode::Serializer::new(&mut bytes);
    |                         --------------   ^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for `E`
    |                         |
    |                         consider giving `serializer` a type
error: aborting due to previous error
error: Could not compile `ipc-channel`.
```

**Comment by jdm** [comment]
This is broken on TravisCI, too.

**Comment by aidanhs** [comment]
Quick workaround is to make the dep in cargo read `bincode = "=1.0.0-alpha2"`.

**Comment by dtolnay** [comment]
Until https://github.com/rust-lang/cargo/issues/2222 is resolved, you should always depend on pre-release version using "=1.0.0-alpha2". Semver makes no guarantee about compatibility between alphaN and alphaN+1.

**Comment by danlrobertson** [comment]
This has been resolved
