### ISSUE TITLE
Preserve sending order upon receiving

### ISSUE THREAD

**Issue by kvark** [servo/ipc-channel#172]
Do I understand correctly that `ipc-channel` doesn't guarantee that the messages (sent from the same sender) are getting received in the same order? ~~I can observe that on OSX with my application.~~ (Edit: nope, turns out to be late night programming syndrome). If that's the case, is there any way/alternative for me to enforce the order?

**Comment by antrik** [comment]
@kvark  `ipc-channel` *should* preserve the order for each sender. If it doesn't, that's a bug.

PS. Please post major changes as follow-up comments rather than just edits: github doesn't send a notification for edits...

**Comment by kvark** [comment]
Thanks @antrik ! I'll re-open if I get a good test case.
