### ISSUE TITLE
Doesn't compile with musl

### ISSUE THREAD

**Issue by kpcyrd** [servo/ipc-channel#192]
I've tried to fix the compile issue on alpine/musl and ran into this problem:

`libc::msghdr` has two fields that don't exist on non-musl, `__pad1` and `__pad2`. Since there is no construcutor and these fields are private, `msghdr` can not be created.

https://github.com/rust-lang/libc/blob/master/src/unix/notbsd/linux/musl/b64/mod.rs

This currently blocks a musl port due to src/platform/unix/mod.rs. Everything else is trivial to fix.

**Comment by waywardmonkeys** [comment]
I think you need to file a bug upstream with `libc` about this?

**Comment by WiSaGaN** [comment]
I am also interested in fixing this. What would be a proper way of fixing this in `libc`? I can create an issue there.
