### ISSUE TITLE
Dependency on not maintained project

### ISSUE THREAD

**Issue by goral09** [servo/ipc-channel#213]
`crossbeam-channel` project it no longer maintained. Why doesn't this one migrate to `crossbeam`?

![image](https://user-images.githubusercontent.com/5120801/49500040-fe853080-f86f-11e8-833e-55ed0e0b3fec.png)

**Comment by dlrobertson** [comment]
Thanks for the inquiry! While the `crossbeam-channel` standalone repo has been archived, `crossbeam` uses cargo workspaces, so the `crossbeam-channel` crate is still maintained (see [crates.io](https://crates.io/crates/crossbeam-channel)) and the associated [cargo workspace](https://github.com/crossbeam-rs/crossbeam/tree/master/crossbeam-channel). We don't include the dependency as a git dependency, so AFAIK we should be using the maintained version of `crossbeam-channel`.
