### ISSUE TITLE
Remove Trait Bounds for Generic `T` in Receiver and Sender.

### ISSUE THREAD

**Issue by gatoWololo** [servo/ipc-channel#235]
Currently IpcSender and Receiver are defined as:
```rust
pub struct IpcSender<T> where T: Serialize {
    ...
}
pub struct IpcReceiver<T> where T: for<'de> Deserialize<'de> + Serialize {
    ...
}
```

This makes it impossible to wrap either Ipc[Sender|Receiver] in my own type, and derive Deserialize and Serialize like so:
```rust
#[derive(Debug, Serialize, Deserialize)]
pub struct IpcReceiver<T> { // MY IpcReceiver
    receiver: ipc::IpcReceiver<(DetThreadId, T)>,
    ...
}
```
See https://github.com/serde-rs/serde/issues/1578 for details.

The solution is fairly straight forward.
1) Get rid of the trait bounds in the struct definition:
```diff
-pub struct IpcReceiver<T> where T: for<'de> Deserialize<'de> + Serialize {
+pub struct IpcReceiver<T> {

-pub struct IpcSender<T> where T: Serialize {
+pub struct IpcSender<T> {
```
2) Get rid of the trait bounds in the implementation blocks for Serialize and Deserialize:
```diff
-impl<'de, T> Deserialize<'de> for IpcReceiver<T> where T: for<'dde> Deserialize<'dde> + Serialize {
+impl<'de, T> Deserialize<'de> for IpcReceiver<T> {

-impl<T> Serialize for IpcReceiver<T> where T: for<'de> Deserialize<'de> + Serialize {
+impl<T> Serialize for IpcReceiver<T> {

-impl<'de, T> Deserialize<'de> for IpcSender<T> where T: Serialize {
+impl<'de, T> Deserialize<'de> for IpcSender<T> {

-impl<T> Serialize for IpcSender<T> where T: Serialize {
+impl<T> Serialize for IpcSender<T> {
```

Number 2 is interesting (I think?): the bounds on `T` are not required since the sender/receiver serialization implementation doesn't depend on `T` being serializable. So in general, it seems it is possible to serialize senders/receivers even when `T` itself is not serializable.

I can make this changes if there is no objection?

**Comment by jdm** [comment]
Sounds reasonable!
