### ISSUE TITLE
Error APIs can be performance sensitive

### ISSUE THREAD

**Issue by jdm** [servo/ipc-channel#254]
[bincode::Error](https://docs.rs/bincode/1.2.1/bincode/type.Error.html) is a Box. Any API in ipc-channel that returns a bincode::Error as part of a result (ie. lots of APIs in ipc.rs) can therefore allocate when there's a failure result. For APIs like try_recv() where they can be called frequently and often, this can lead to performance surprises, particularly in code like `if let Ok(msg) = receiver.try_recv()` where the error case is completely discarded.

For the inprocess backend it's actually even worse - https://github.com/servo/ipc-channel/blob/84a1483420ba60110c2388aaa3062511339976d1/src/platform/inprocess/mod.rs#L384-L404 means that we first create a std::Error (which is a Box), then box that inside a bincode error. This shows up really high in some profiles that rely on try_recv being called every frame.

**Comment by asajeffrey** [comment]
Can we make `try_rev` return an `Result<T, Option<Error>>` so at least we're not allocating a box in that case?

**Comment by jdm** [comment]
Yes; I'm trying out returning a special TryRecvError enum that doesn't box in the common cases of empty channel/disconnected.

**Comment by mitsuhiko** [comment]
The `try_recv` case would generally be nice to handle differently. Currently one needs to do something like this from my understanding:

```rust
fn is_ipc_timeout(err: &ipc_channel::Error) -> bool {
    if let ipc_channel::ErrorKind::Io(ref io) = &**err {
        match io.kind() {
            io::ErrorKind::TimedOut => true,
            io::ErrorKind::WouldBlock => true,
            _ => false,
        }
    } else {
        false
    }
}
```

**Comment by jdm** [comment]
@mitsuhiko Does #259 address your needs?
