### ISSUE TITLE
IpcBytesSender::send will hang up when receiver is not work.

### ISSUE THREAD

**Issue by jmjoy** [servo/ipc-channel#275]
OS: Linux（5.4.50）

Test code:

```rust
use ipc_channel::ipc::bytes_channel;

fn main() {
    let (sender, _receiver) = bytes_channel().unwrap();

    for i in  0..1000 {
        println!("count: {}", i);
        sender.send(b"...").unwrap();
    }
}
```

Result (Hang up when count is 278):
```
...
count: 275
count: 276
count: 277
count: 278
```

If it really will hang up, may be prompt on the [document](https://docs.rs/ipc-channel/0.15.0/ipc_channel/ipc/fn.bytes_channel.html)?

**Comment by jdm** [comment]
It would be useful to step through [this code](https://github.com/servo/ipc-channel/blob/master/src/platform/unix/mod.rs#L240) to find out where the hang is coming from.
