### ISSUE TITLE
Trivial Example Not Working

### ISSUE THREAD

**Issue by patientplatypus6** [servo/ipc-channel#305]
So I have as trivial an example as I can make and it doesn't appear to work. It may be something stupid, but I thought I'd put it here in case someone comes along and is debugging their code. 

So I have a rust cargo called `process_handler` that creates a `IpcOneShotServer` and then spawns a server. (NOTE: most of the code comes from the examples as shown in the `test.rs` file linked in the repo). 

```
use std::process::Command;
use ipc_channel::ipc::{self, IpcOneShotServer, IpcSender, IpcReceiver};

fn main() {
    
    let datavec = vec![("Peter".to_string(), "36".to_string())];
    
    let guiserver = spawn_server(
                  "/Users/peterweyand/Code/rustprojects/project1.1/project1_1/process_handler/src/rungui.sh".to_string(), 
                  // &server_args
                  &server_name0
              );
}

pub fn spawn_server(address:String, test_name: &str) -> std::process::Child {
    Command::new(address) 
        .arg(test_name)
        .spawn()
        .expect("failed to execute server process")
}
```

which calls a bash file like so 

```
#!/bin/bash

echo "inside rungui.sh"
echo "First Parameter of the script is $1"

cd /Users/peterweyand/Code/rustprojects/project1.1/project1_1
cargo build && cargo run -- $1
```

which calls my cargo that I want to access the IpcSender on - 

```
use iced::widget::{button, container, row, column, text, text_input};
use iced::{executor, Application, Command, Length, Settings};
use ipc_channel::ipc::{self, IpcOneShotServer, IpcSender, IpcReceiver};
use iced::Color;
// use iced::widget::column;
use self::theme::Theme;
use self::widget::Element;
use std::collections::HashMap;
use std::process::Command as ProcessCommand;
use std::env;
use std::io;
use std::{thread, time};

fn main() {
    println!("&cloned_string: {:?}", args[1].clone());
    let tx2 = IpcSender::<Vec<(String, String)>>::connect(args[1].clone()).unwrap();     
}
```

Which produces the following result - 

```
&cloned_string: "org.rust-lang.ipc-channel.8687042407079962014"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: Unknown(1102) }', src/main.rs:59:76
```

According to here `https://doc.rust-lang.org/error_codes/error-index.html` there *is no* error code 1102. 

So, why is this failing? I would expect that since the latter cargo is a child process it should be able to access the `IpcSender`. This isn't fancy at all, just accessing the messages between processes. I'm not wrapping one channel or server in another or anything like that.

Thanks.

**Comment by patientplatypus6** [comment]
I've opened a stackoverflow issue here https://stackoverflow.com/posts/74831633/edit. 

I've also asked the question in their github issues: https://github.com/servo/ipc-channel/issues/305

You can see the repo here: https://github.com/patientplatypus6/icedrustplay. cd into the process handler folder and cargo build and cargo run.

**Comment by jdm** [comment]
I don't know what to make of your repo, where the majority of the code is commented out and the main process looks like it exits immediately after starting the server.

**Comment by jdm** [comment]
A self-contained example of the problem that can be compiled and run immediately would be the easiest way to understand the problem.

**Comment by patientplatypus6** [comment]
cd into the folder process_handler. cargo build and cargo run. `https://github.com/patientplatypus6/icedrustplay/blob/main/process_handler/src/main.rs#L30` runs the bash script `https://github.com/patientplatypus6/icedrustplay/blob/main/process_handler/src/rungui.sh` which cargo builds and runs the top level folder. `https://github.com/patientplatypus6/icedrustplay/blob/main/src/main.rs` 

Apologies that the process_handler is in a subfolder as opposed to being top level. That is a little confusing. 

`https://github.com/patientplatypus6/icedrustplay/blob/main/src/main.rs#L59` is the field that is not compiling. 

`let tx2 = IpcSender::<Vec<(String, String)>>::connect(args[1].clone()).unwrap();`

which is weird because 

`https://github.com/patientplatypus6/icedrustplay/blob/main/src/main.rs#L50` 

`println!("&cloned_string: {:?}", args[1].clone());`

shows that the argument is being passed successfully from the process_handler crate through the bash script and into the crate at top level.

Other than the process_handler folder being a subfolder you have to cd into and then run cargo build and cargo run there isn't anything about this that is more than trivial.

**Comment by jdm** [comment]
The error goes away if I add this code to the bottom of the process_handler main function:
```
    loop {
        std::thread::sleep_ms(1000);
    }
```
The server is exiting immediately after starting the server, so the child has nothing to connect to when it gets a chance to run.

**Comment by patientplatypus6** [comment]
Oh, that's dumb. OK, thanks for the help.
