### ISSUE TITLE
Do not panic in OsIpcOneShotServer::new

### ISSUE THREAD

**Issue by xmakro** [servo/ipc-channel#350]
Currently `OsIpcOneShotServer::new` can panic in ([see code](https://github.com/servo/ipc-channel/blob/main/src/platform/unix/mod.rs#L676)):

```
let temp_dir = tempfile::Builder::new().tempdir().unwrap();
```

It would be good to raise the error instead. This would require modifying `UnixError` to have a variant `Io(io::Error)`. This makes the `UnixError` struct larger and non copyable, but `UnixError` is converted to `io::Error` later on, this might be okay.

If you agree with this change, I'd send a PR.

**Comment by jdm** [comment]
Agreed! I would merge a PR.
