### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by retep998** [servo/ipc-channel#36]
Just creating this issue to keep track of implementing Windows support.

**Comment by vvuk** [comment]
FWIW, I'm working on this in https://github.com/vvuk/ipc-channel/tree/win32 -- let me know if you already have progress and we can figure out where to go.

**Comment by zsck** [comment]
Hey all,
I was just wondering what the status of Windows support is.

**Comment by antrik** [comment]
@zsck it's almost there: I just need to finish reviewing the current iteration of https://github.com/servo/ipc-channel/pull/108 . (And hopefully not find any more serious issues in the process :-) )

**Comment by Boscop** [comment]
Any update on this? :)

**Comment by jdm** [comment]
@Boscop #108 still has some outstanding review comments that need to be addressed.

**Comment by CAD97** [comment]
For future visitors, work continues in #166

**Comment by demurgos** [comment]
The PR #272 to add support for Windows was merged. Hopefully there will be a new release soon with Windows support.

**Comment by KiChjang** [comment]
@demurgos As I understand it, `0.15.0` has already been published [in crates.io](https://crates.io/crates/ipc-channel) with #272 included with it. What sort of problems are you encountering?

**Comment by jdm** [comment]
Closing since Windows support exists and has been published. Please file new issues for any problems!
