### ISSUE TITLE
Option<char> values are corrupted when sent over an ipc channel

### ISSUE THREAD

**Issue by jdm** [servo/ipc-channel#84]
This test fails on OS X:
```rust
#[test]
fn simple_char() {
    let ch = Some('a');
    let (tx, rx) = ipc::channel().unwrap();
    tx.send(ch).unwrap();
    let received_ch = rx.recv().unwrap();
    assert_eq!(ch, received_ch);
}
```
yields
```
---- test::simple_char stdout ----
	thread 'test::simple_char' panicked at 'assertion failed: `(left == right)` (left: `Some('a')`, right: `Some('\u{0}')`)', test.rs:394
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    test::simple_char

test result: FAILED. 46 passed; 1 failed; 0 ignored; 0 measured
```

**Comment by jdm** [comment]
Casting the char to a u64 value makes it work fine. My money is on serde being at fault here.

**Comment by jdm** [comment]
The `Option` isn't necessary; a simple char value is enough to trigger this.

**Comment by oli-obk** [comment]
which serde version are you using? The yanked 0.7.6 had [a bug](https://github.com/serde-rs/serde/pull/349/files) that was fixed in 0.7.7

**Comment by nox** [comment]
@oli-obk 0.7.11

**Comment by oli-obk** [comment]
ok. I'm on it.

**Comment by oli-obk** [comment]
fix in https://github.com/TyOverby/bincode/pull/81

**Comment by KiChjang** [comment]
So is it true now that if we upgrade serde to 0.7.12, this issue would be solved?

**Comment by jdm** [comment]
Upgrading bincode solves it.
